### ISSUE TITLE
Review Process Typo

### ISSUE THREAD

**Issue by TasmanGC** [distillpub/post--editorial-update-2018#5]
> Review Process
> When we started Distill, we adopted a pretty radical review process. We knew that most researchers didn’t have the full skill set — especially the design skills — needed to write the kind of articles Distill aspires to. For that reason, we provided extensive mentorship and assistance to help **autohrs** improve articles.

autohrs=authors

**Comment by ludwigschubert** [comment]
Thanks, already fixed but not yet live!
